# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliner',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
