# Generated by Django 4.2.4 on 2023-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0002_oneliner_updated_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliner',
            name='unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
