# Generated by Django 4.2.4 on 2023-09-02 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneliners', '0004_snapshotoneliner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLinerSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('line', models.TextField()),
                ('explanation', models.TextField()),
                ('limitations', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('was_tweeted', models.BooleanField(default=False)),
                ('unpublished', models.BooleanField(default=False)),
                ('created_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('oneliner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneliners.oneliner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SnapshotOneLiner',
        ),
    ]
