# Generated by Django 4.2.4 on 2023-09-02 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0005_onelinersnapshot_delete_snapshotoneliner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onelinersnapshot',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onelinersnapshot',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='onelinersnapshot',
            name='limitations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onelinersnapshot',
            name='unpublished',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='onelinersnapshot',
            name='was_tweeted',
            field=models.BooleanField(),
        ),
    ]
