# Generated by Django 4.2.5 on 2023-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0007_alter_alternativeoneliner_id_alter_hackerprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliner',
            name='published_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
