# Generated by Django 4.2.5 on 2023-09-24 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0008_oneliner_published_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('function', 'Function'), ('audience', 'Audience'), ('scenario', 'Scenario'), ('language-feature', 'Language feature'), ('complexity', 'Complexity')], max_length=30)),
                ('name', models.SlugField(max_length=30)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OnelinerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneliners.category')),
                ('oneliner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneliners.oneliner')),
            ],
            options={
                'unique_together': {('oneliner', 'category')},
            },
        ),
    ]
