# Generated by Django 4.2.5 on 2023-09-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0009_category_onelinercategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('type', 'name')},
        ),
    ]
