# Generated by Django 4.2.5 on 2023-09-28 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0011_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
