# Generated by Django 4.2.5 on 2023-09-29 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0012_tag_created_dt_tag_updated_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OnelinerCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneliners.command')),
                ('oneliner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneliners.oneliner')),
            ],
            options={
                'unique_together': {('oneliner', 'command')},
            },
        ),
    ]
