# Generated by Django 4.2.5 on 2023-10-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0013_command_onelinercommand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneLinerTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
